name: https://mikiashwt.github.io/
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme


title: Mikias Woldetensae: Personal Portfolio
description: This is my first personal portfolio. I plan to use it to showcase my technical and scientific background.  
